//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridDemo.Web.Layouts.Sublayouts.Modules
{


	public partial class DemoColorBox
	{
	}
}
